import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/db/prisma';
import { finalizePayment } from '@/lib/payments/finalize';
import { parseCallback } from '@/lib/payments/daraja';

/**
 * Safaricom Daraja webhook — called after an STK push resolves.
 *
 * Public endpoint (no session): Safaricom's servers POST the raw result here.
 * The tenant's browser is not involved, so this route answers on its own.
 *
 * Daraja does not sign its callbacks, so the ONLY safe match key is the
 * `CheckoutRequestID` issued when the push was sent — it is generated by
 * Safaricom, stored here at initiation, and never exposed to the tenant. There
 * is deliberately no phone+amount fallback: matching on guessable values would
 * let anyone finalize an invoice they have not paid.
 */
export async function POST(req: NextRequest) {
  const body = await req.text();

  let callback;
  try {
    callback = parseCallback(body);
  } catch {
    return NextResponse.json({ ResultCode: 1, ResultDesc: 'Invalid payload' }, { status: 400 });
  }

  const { checkoutRequestId } = callback;
  if (!checkoutRequestId) {
    return NextResponse.json({ ResultCode: 1, ResultDesc: 'Missing CheckoutRequestID' }, { status: 400 });
  }

  // Only PENDING records qualify, so a late or replayed callback can never
  // resurrect a payment already marked FAILED or CANCELLED.
  const payment = await prisma.payment.findFirst({
    where: { status: 'PENDING', checkoutRequestId },
    select: {
      id: true,
      amount: true,
      checkoutRequestId: true,
      phoneNumber: true,
      invoice: { select: { balance: true } },
    },
  });

  if (!payment) {
    // Safaricom retries a non-2xx a few times; 404 tells it to stop. This is
    // also the answer for a replayed callback against an already-settled
    // payment — which is correct, nothing more to do.
    console.warn(`[Daraja] No pending payment for CheckoutRequestID ${checkoutRequestId}`);
    return NextResponse.json({ ResultCode: 1, ResultDesc: 'Payment not found' }, { status: 404 });
  }

  if (callback.succeeded) {
    // The receipt is what the tenant sees on their statement — fall back to the
    // CheckoutRequestID only if Safaricom somehow omitted it.
    const transactionCode = callback.mpesaReceipt || checkoutRequestId;
    const amount = callback.amount !== undefined && callback.amount > 0 ? callback.amount : payment.amount;

    if (callback.amount !== undefined && callback.amount > 0 && callback.amount !== Math.round(payment.amount)) {
      console.warn(
        `[Daraja] Callback amount for ${payment.id} differs from recorded: recorded ${payment.amount}, callback ${callback.amount}`
      );
    }

    await finalizePayment(payment.id, {
      transactionCode,
      checkoutRequestId,
      phoneNumber: callback.phoneNumber || payment.phoneNumber,
      amount,
    });
  } else if (callback.failed) {
    // Terminal failure — atomically, so a racing query cannot double-handle it.
    await prisma.payment.updateMany({
      where: { id: payment.id, status: 'PENDING' },
      data: { status: 'FAILED' },
    });
    console.log(
      `[Daraja] Payment ${payment.id} failed (code ${callback.resultCode}): ${callback.resultDesc ?? 'no detail'}`
    );
  } else {
    // No ResultCode at all — acknowledge but leave the payment PENDING so the
    // status poll can still resolve it.
    console.log(`[Daraja] Callback for ${payment.id} carried no ResultCode — keeping PENDING`);
  }

  // Daraja expects an explicit acknowledgement; a non-zero ResultCode would
  // make Safaricom flag the endpoint as misbehaving.
  return NextResponse.json({ ResultCode: 0, ResultDesc: 'Accepted' });
}
