import { PdfDocument } from '@/lib/pdf';
import { formatCurrency, formatDate } from '@/lib/utils/format';

export interface LeasePdfData {
  id: string;
  startDate: string | Date;
  endDate: string | Date;
  monthlyRent: number;
  depositAmount: number;
  status: string;
  terms?: string | null;
  isDigitalSignature: boolean;
  createdAt?: string | Date;
  tenant?: {
    firstName: string;
    lastName: string;
    email?: string | null;
    phone?: string | null;
    idNumber?: string | null;
  } | null;
  unit?: {
    unitNumber: string;
    monthlyRent?: number;
    bedrooms?: number;
    bathrooms?: number;
    property?: { name: string; address?: string; city?: string } | null;
  } | null;
  createdBy?: { firstName: string; lastName: string; role?: string } | null;
}

export function buildLeasePdf(lease: LeasePdfData): Buffer {
  const pdf = new PdfDocument();
  const tenantName = lease.tenant ? `${lease.tenant.firstName} ${lease.tenant.lastName}`.trim() : 'Tenant';
  const propertyName = lease.unit?.property?.name || 'Property';
  const address = [lease.unit?.property?.address, lease.unit?.property?.city]
    .filter(Boolean)
    .join(', ');

  pdf
    .heading('RESIDENTIAL LEASE AGREEMENT')
    .muted(`${propertyName}${address ? ` — ${address}` : ''}`)
    .muted(`Lease reference: ${lease.id}`)
    .divider()
    .text(`This Residential Lease Agreement ("Agreement") is made between the Landlord of ${propertyName} and ${tenantName} ("Tenant") for the room described below.`, { size: 'sm' })
    .gap(6)
    .subheading('1. Parties')
    .keyValue('Tenant', tenantName)
    .keyValue('Tenant email', lease.tenant?.email || '-')
    .keyValue('Tenant phone', lease.tenant?.phone || '-')
    .keyValue('Landlord / Manager', lease.createdBy ? `${lease.createdBy.firstName} ${lease.createdBy.lastName}`.trim() : 'Boma Yangu')
    .gap(4)
    .subheading('2. Premises')
    .keyValue('Property', propertyName)
    .keyValue('Room / Unit', lease.unit?.unitNumber || '-')
    .keyValue('Address', address || '-')
    .gap(4)
    .subheading('3. Term')
    .keyValue('Start date', formatDate(lease.startDate))
    .keyValue('End date', formatDate(lease.endDate))
    .keyValue('Status', lease.status)
    .gap(4)
    .subheading('4. Rent and Deposit')
    .keyValue('Monthly rent', formatCurrency(lease.monthlyRent))
    .keyValue('Deposit held', formatCurrency(lease.depositAmount))
    .text('Rent is payable in advance on or before the 5th day of each month via M-Pesa to the payment details shared by the Landlord.', { size: 'sm' })
    .gap(4)
    .subheading('5. General Terms')
    .text(
      lease.terms ||
        'The Tenant agrees to keep the premises clean, pay utilities where applicable, and not sublet the room without written consent. Either party may terminate this Agreement with one month written notice.',
      { size: 'sm' }
    )
    .gap(10)
    .subheading('6. Signatures')
    .keyValue('Landlord', '____________________')
    .keyValue('Tenant', '____________________')
    .keyValue('Date', formatDate(lease.createdAt || new Date()))
    .muted(lease.isDigitalSignature ? 'Digitally signed via Boma Yangu.' : 'Physical signature required.')
    .footer('Generated by Boma Yangu — Boma Yangu rental management');

  return pdf.build();
}
